# fly.toml app configuration file generated for bosterback on 2023-11-14T04:39:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bosterback"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
